config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :projects do
    resources :images do
      resources :regions do
        resource :payoffs
      end

      member do
        get 'download'
      end
    end
  end

  root to: 'projects#index'

end

app/models/image.rb
# encoding: utf-8

class Image < ActiveRecord::Base
  belongs_to :project
  has_many :regions

  mount_uploader :original, ImageUploader

  validates :project, :presence => true
  validates :name, :presence => true
  validates :original,
    :presence => true
  validate :original_max_size

  private

  def original_max_size
    errors[:original] << "should be less than 10MB" if original.size > 10.megabytes
  end
end

app/models/payoff.rb
require 'live_paper'

class Payoff < ActiveRecord::Base
  include LivePaper

  belongs_to :project
  has_many :regions

  validates :project, :presence => true
  validates :url,
    :presence => true,
    :allow_blank => false,
    :format => { with: URI::regexp(%w(http https)), message: "must be a URL" }
  validates :payoff_api_url,
    :format => { with: URI::regexp(%w(http https)), message: "must be a URL" },
    :allow_nil => true

  before_save :sync_with_livepaper
  after_destroy :destroy_with_livepaper

  private

  def sync_with_livepaper
    #connect to livepaper
    user = self.project.user
    lp = LivePaper.auth({id: user.client_id, secret: user.client_secret})

    if not self.payoff_api_url
      payoff = Payoff.create(name: self.name, type: Payoff::TYPE[:WEB], url: self.url)
      self.payoff_api_url = "#{Payoff.api_url}/#{payoff.id}"
    elsif self.url_changed?
      payoff = Payoff.get(self.payoff_api_url.split('/')[-1])
      payoff.url = self.url
      payoff.update
    end
  end
  
  def destroy_with_livepaper
    payoff = Payoff.get(self.payoff_api_url.split('/')[-1])
    payoff.delete
  end
end

app/models/project.rb
# encoding: utf-8

class Project < ActiveRecord::Base
  belongs_to :user
  has_many :images
  has_many :payoffs

  validates :user, :presence => true, :allow_blank => false
  validates :name, :presence => true, :allow_blank => false
  validates :client, :presence => true, :allow_blank => false
  validates :logo,
    :presence => true,
    :allow_blank => false,
    :format => { with: URI::regexp(%w(http https)), message: "must be a URL" }
end

app/models/region.rb
require 'live_paper'

class Region < ActiveRecord::Base
  include LivePaper

  belongs_to :image
  belongs_to :payoff

  validates :name, :presence => true
  validates :image, :presence => true
  validates :payoff, :presence => true

  accepts_nested_attributes_for :payoff

  before_save :sync_with_livepaper
  after_destroy :destroy_with_livepaper

  private
  
  def sync_with_livepaper
    #connect to livepaper
    user = self.image.project.user
    lp = LivePaper.auth({id: user.client_id, secret: user.client_secret})

    # If no trigger has been created for this region, create it
    if self.trigger_api_url.blank?
      # Generate a trigger name based on the region's name
      trigger_name = "#{self.name}_trigger"
      
      # Create remote resouces
      trigger   = WmTrigger.create(name: trigger_name)
      puts self.payoff.payoff_api_url
      link      = Link.create(payoff_id: self.payoff.payoff_api_url.split('/')[-1], trigger_id: trigger.id, name: "#{self.name}_#{self.payoff.name}_link")

      # Save back URL's
      self.trigger_api_url  = "#{Trigger.api_url}/#{trigger.id}"
      self.link_api_url     = "#{Link.api_url}/${link.id}"
    else
      # If the name of the region has changed, update the trigger appropriately
      if self.name_changed?
        trigger = WmTrigger.get(self.trigger_api_url.split("/")[-1])
        trigger.name = self.name
        trigger.update
      end

      # If the payoff has changed, it may be a new payoff, update the link
      if self.payoff_changed?
        link = Link.get(self.link_api_url.split("/")[-1])
        link.payoff_id = self.payoff.payoff_api_url.split("/")[-1]
        link.update
      end
    end
  end

  def destroy_with_livepaper
    trigger = WmTrigger.get(self.trigger_api_url.split("/")[-1])
    trigger.delete

    link = Link.get(self.link_api_url.split("/")[-1])
    link.delete
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :username, :presence => true, :allow_blank => false

  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
    devise_parameter_sanitizer.for(:sign_up) << :client_id
    devise_parameter_sanitizer.for(:sign_up) << :client_secret
  end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
	
	before_filter :get_project

	def show
		@image = @project.images.find(params[:id])
		@regions = @image.regions
	end

	def new
		@image = @project.images.build
	end

	def create
		@image = @project.images.build(image_params)

		if @image.save
			redirect_to [@project, @image]
		else
			render :new
		end
	end

	def edit
		@image = @project.images.find(params[:id])
	end

	def update
		@image = @project.iamges.find(params[:id])
	
		if @image.update_attribtes(image_params)
			redirect_to [@project, @image]
		else
			render :edit
		end
	end

	def delete
		@image = @project.images.find(params[:id])
		@image.destroy
		redirect_to @project
	end

	def download
		@image = @project.images.find(params[:id])
		send_file(@image.original.path, filename: File.basename(@image.original.path), type: "image/jpg")
	end

	private

	    def image_params
	      params.require(:image).permit(:name, :original, :project)
	    end

	    def get_project
	    	@project = Project.find(params[:project_id])
	    end
end

app/controllers/payoffs_controller.rb
class PayoffsController < ApplicationController
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :authenticate_user!

  def index
    @projects = current_user.projects
  end

  def show
    @project = Project.find(params[:id])
    @images = @project.images
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user

    if @project.save
      redirect_to @project
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update_attributes(project_params)
      redirect_to @project
    else
      render :edit
    end
  end

  def delete
    @project = Project.find(params[:id]).destroy
    redirect_to projects_path
  end

  private

    def project_params
      params.require(:project).permit(:name, :description, :user, :client, :logo)
    end
end

app/controllers/regions_controller.rb
class RegionsController < ApplicationController

  before_filter :get_project_and_image

  def new
    @region = @image.regions.build
    @region.payoff = Payoff.new
  end

  def create
    @region = @image.regions.create(region_params)
    @region.payoff = @project.payoffs.create(payoff_params)

    if @region.save
      redirect_to [@project, @image]
    else
      render :new
    end
  end

  def edit
    @region = @image.regions.find(params[:id])
  end

  def update
    @region = @image.regions.find(params[:id])

    if @region.update_attributes(region_params) and @region.payoff.update_attributes(payoff_params)
      redirect_to [@project, @image]
    else
      render :edit
    end
  end

  def delete
    @region = @image.regions.find(params[:id]).destroy
    redirect_to [@project, @image]
  end

  private

    def region_params
      params.require(:region).permit(:name, :top, :left, :width, :height, :watermark_strength, :watermark_resolution, :payoff_attributes)
    end

    def payoff_params
      params[:region].require(:payoff_attributes).permit(:name, :url)
    end

    def get_project_and_image
      @project = Project.find(params[:project_id])
      @image = @project.images.find(params[:image_id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/payoffs_helper.rb
module PayoffsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/views/images/new.html.erb
<h1>New Image</h1>

<%= form_for [@project, @image], multipart: true do |f| %>

	<% if @image.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@image.errors.count, "error") %> prohibited this project from being saved:
			</h2>

			<ul>
				<% @image.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :original %><br />
		<%= f.file_field :original %>
	</div>

	<div class="field">
		<%= f.submit %>
	</div>
<% end %>

app/views/images/show.html.erb
<h1 class="divider">Image: <%= @image.name %></h1>

<div class="col-xs-3">
  <%= link_to "Download Image", download_project_image_path(@project, @image) %>

  <h2 class="divider">Regions</h2>

  <%= link_to "New Region", new_project_image_region_path(@project, @image) %>

  <ul>
  <% for region in @regions %>
  <li>
    <%= region.name %> - Start: <%= region.top %>, <%= region.left %> - Size: <%= region.width %>, <%= region.height %> - Payoff: <%= region.payoff.url %>
  </li>
  <% end %>
  </ul>
</div>

<div class="col-xs-9">
  <p><%= image_tag @image.original.url %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Watermarker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="main-container" class="container-fluid">
	<header class="row">
		<% if user_signed_in? %>
		<div style="float: right">
			Hi, <%= current_user.username %>! <%= link_to "Logout", destroy_user_session_path(), method: :DELETE %>
		</div>
		<% end %>
		<h2>Watermarker</h2>
	</header>

	<div class="row">
		<div class="notice"><%= notice %></div>
		<% if alert %>
		<div class="alert"><%= alert %></div>
		<% end %>
		<%= yield %>
	</div>
</body>
</html>

app/views/projects/edit.html.erb
<h1>Projects#edit</h1>
<p>Find me in app/views/projects/edit.html.erb</p>

app/views/projects/index.html.erb
<h1>My Projects</h1>

<ul>
<% for project in @projects %>
<li><%= link_to project.name, project_url(project) %></li>
<% end %>
</ul>

<p><%= link_to "New Project", new_project_url %></p>

app/views/projects/new.html.erb
<h1>Create a New Project</h1>

<%= form_for @project do |f| %>

<% if @project.errors.any? %>
	<div id="error_explanation">
		<h2>
			<%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:
		</h2>

		<ul>
			<% @project.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
		</ul>
	</div>
<% end %>

<div class="field">
	<%= f.label :name %><br />
	<%= f.text_field :name %>
</div>

<div class="field">
	<%= f.label :description %><br />
	<%= f.text_field :description %>
</div>

<div class="field">
	<%= f.label :client %><br />
	<%= f.text_field :client %>
</div>

<div class="field">
	<%= f.label :logo %><br />
	<%= f.url_field :logo %>
</div>

<div class="field">
	<%= f.submit %>
</div>

<% end %>

app/views/projects/show.html.erb
<h1 class="divider"><%= @project.name %></h1>

<div class="col-xs-2">
	<p><%= image_tag @project.logo, size: "128x128" %></p>

	<label>Project Description</label>
	<p><%= @project.description %></p>

	<label>Project Client</label>
	<p><%= @project.client %></p>

	<p><%= link_to "Edit this project", edit_project_url(@project) %></p>
</div>

<div class="col-xs-10">
<h2 class="divider">Images</h2>
<p><%= link_to "New Image", new_project_image_url(@project) %></p>
<ul>
<% for image in @images %>
	<li><%= link_to image.name, project_image_url(@project, image) %>: <%= image.height %>x<%= image.width %></li>
<% end %>
</ul>
</div>

app/views/regions/new.html.erb
<h1>Region Details</h1>

<%= form_for [@project, @image, @region] do |f| %>

<% if @region.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@region.errors.count, "error") %> prohibited this region from being saved:
    </h2>

    <ul>
      <% @region.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= f.label :name %><br />
  <%= f.text_field :name %>
</div>

<h3>Payoff Details</h3>
<%= f.fields_for :payoff do |payoff_form| %>
  <div class="field">
    <%= payoff_form.label :name %>
    <%= payoff_form.text_field :name %>
  </div>

  <div class="field">
    <%= payoff_form.label :destination %>
    <%= payoff_form.text_field :url %>
  </div>  
<% end %>

<h3>Dimensions</h3>
<div class="field">
  <%= f.label :left %><br />
  <%= f.text_field :left %>
</div>

<div class="field">
  <%= f.label :top %><br />
  <%= f.text_field :top %>
</div>

<div class="field">
  <%= f.label :width %><br />
  <%= f.text_field :width %>
</div>

<div class="field">
  <%= f.label :height %><br />
  <%= f.text_field :height %>
</div>

<h3>Watermark Details</h3>
<div class="field">
  <%= f.label :watermark_strength %><br />
  <%= f.text_field :watermark_strength %>
</div>

<div class="field">
  <%= f.label :watermark_resolution %><br />
  <%= f.text_field :watermark_resolution %>
</div>

<div class="field">
  <%= f.submit %>
</div>

<% end %>